# Generated by Django 5.1.7 on 2025-04-19 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='booked_seats',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='movie_posters/'),
        ),
        migrations.AlterField(
            model_name='show',
            name='format',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='show',
            name='language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='show',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='movie_app.movie'),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_time',
            field=models.DateTimeField(),
        ),
    ]
