# Generated by Django 5.1.7 on 2025-04-11 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='time',
            new_name='show_time',
        ),
        migrations.RemoveField(
            model_name='show',
            name='screen',
        ),
        migrations.AddField(
            model_name='show',
            name='format',
            field=models.CharField(default='2D', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='language',
            field=models.CharField(default='2D', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='show',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='authentication.movie'),
        ),
    ]
