# Generated by Django 5.1.7 on 2025-04-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_time_show_show_time_remove_show_screen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='booked_seats',
            field=models.TextField(default=''),
        ),
    ]
